[furble]
build_flags = -Wall -D FURBLE_VERSION=\"${sysenv.FURBLE_VERSION}\" -DCORE_DEBUG_LEVEL=5 -DCONFIG_NIMBLE_CPP_ENABLE_GAP_EVENT_CODE_TEXT

[env]
platform = espressif32
board_build.f_cpu = 80000000L
upload_protocol = esptool
framework = arduino
lib_deps =
  M5GFX@0.1.16
  M5Unified@0.1.16
  mikalhart/TinyGPSPlus@1.0.3
  https://github.com/h2zero/NimBLE-Arduino#44a69ed

[env:m5stick-c]
board = m5stick-c
build_flags = ${furble.build_flags} -D ARDUINO_M5STICK_C=1

[env:m5stick-c-plus]
board = m5stick-c
build_flags = ${furble.build_flags} -D ARDUINO_M5STICK_C_PLUS=1

[env:m5stack-core]
board = m5stack-core-esp32
build_flags = ${furble.build_flags} -D ARDUINO_M5STACK_CORE_ESP32=1

[env:m5stack-core2]
board = m5stack-core2
build_flags = ${furble.build_flags} -D ARDUINO_M5STACK_CORE2=1
