#ifndef NIMBLE_STUB_SYSCFG_H_
#define NIMBLE_STUB_SYSCFG_H_

#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include "nimble/nimble_npl.h"
#include "esp_bt.h"
#include "esp_err.h"

#ifndef CONFIG_BT_NIMBLE_ENABLED
#define CONFIG_BT_NIMBLE_ENABLED 1
#endif

#ifndef MYNEWT_VAL
#define MYNEWT_VAL(x) MYNEWT_VAL_##x
#endif

#ifndef MYNEWT_VAL_BLE_ROLE_CENTRAL
#define MYNEWT_VAL_BLE_ROLE_CENTRAL 1
#endif
#ifndef MYNEWT_VAL_BLE_ROLE_OBSERVER
#define MYNEWT_VAL_BLE_ROLE_OBSERVER 1
#endif
#ifndef MYNEWT_VAL_BLE_ROLE_PERIPHERAL
#define MYNEWT_VAL_BLE_ROLE_PERIPHERAL 1
#endif
#ifndef MYNEWT_VAL_BLE_ROLE_BROADCASTER
#define MYNEWT_VAL_BLE_ROLE_BROADCASTER 0
#endif
#ifndef MYNEWT_VAL_BLE_EXT_ADV
#define MYNEWT_VAL_BLE_EXT_ADV 0
#endif
#ifndef MYNEWT_VAL_BLE_L2CAP_COC_MAX_NUM
#define MYNEWT_VAL_BLE_L2CAP_COC_MAX_NUM 0
#endif
#ifndef MYNEWT_VAL_BLE_MAX_CONNECTIONS
#define MYNEWT_VAL_BLE_MAX_CONNECTIONS 3
#endif
#ifndef MYNEWT_VAL_BLE_GATT_CLIENT
#define MYNEWT_VAL_BLE_GATT_CLIENT 1
#endif
#ifndef MYNEWT_VAL_BLE_GATT_SERVER
#define MYNEWT_VAL_BLE_GATT_SERVER 1
#endif
#ifndef MYNEWT_VAL_BLE_ATT_PREFERRED_MTU
#define MYNEWT_VAL_BLE_ATT_PREFERRED_MTU 256
#endif

#ifndef CONFIG_BT_NIMBLE_MAX_CONNECTIONS
#define CONFIG_BT_NIMBLE_MAX_CONNECTIONS MYNEWT_VAL_BLE_MAX_CONNECTIONS
#endif
#ifndef CONFIG_BT_NIMBLE_ATT_PREFERRED_MTU
#define CONFIG_BT_NIMBLE_ATT_PREFERRED_MTU MYNEWT_VAL_BLE_ATT_PREFERRED_MTU
#endif

#endif
