name: PlatformIO CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run clang-format style check
        uses: jidicula/clang-format-action@v4.9.0
        with:
          clang-format-version: '13'
          check-path: '.'
          exclude-regex: 'lib/M5ez/examples'

  # This workflow contains a matrix of build platforms
  build:
    strategy:
      matrix:
        platform:
          - m5stick-c
          - m5stick-c-plus
          - m5stack-core
          - m5stack-core2

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Build furble (${{ matrix.platform }})
        run: platformio run -e ${{ matrix.platform }}

  success:
    runs-on: ubuntu-latest
    needs:
      - format
      - build
    steps:
      - run: echo "Success"!
